# BoW and n-grams

Bag of Words representations. Word n-grams. Char-ngrams.

In [1]:
documents = [
    'frase en castellano',
    'english sentence',
    'esta frase no esta en english',
    'estos documentos tienen muy poco sentido',
    'el documento es un conjunto de frases',
    'Vim es mucho mejor que emacs.'
]

Bag of Words (BoW) ->  1-grams.

histogram of the words within the text -> Count the appearences of each word 

How do we get the vocabulary? Simply map words from training set to a dictionary.

In [79]:
vocabulary = {}
inverse_vocabulary = {}
for doc in documents:
    for token in doc.split(' '):
        if token not in vocabulary:
            vocabulary[token] = len(vocabulary)
            inverse_vocabulary[len(inverse_vocabulary)] = token

In [80]:
print(vocabulary)

{'muy': 10, 'sentido': 12, 'frase': 0, 'conjunto': 17, 'documento': 14, 'un': 16, 'documentos': 8, 'de': 18, 'esta': 5, 'castellano': 2, 'en': 1, 'el': 13, 'tienen': 9, 'poco': 11, 'english': 3, 'sentence': 4, 'no': 6, 'estos': 7, 'es': 15, 'frases': 19}


numpy makes representing this type of data incredibly easy. like C arrays.

When working with data that we may use as features, try as soon as possible to work with numpy arrays.

Matrix Manipulation is fairly important along the course.

In [71]:
import numpy as np

In [37]:
new_representation_np = np.zeros((len(vocabulary)), dtype='int32')
new_representation_np

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [22]:
string = 'documento en castellano'

In [57]:
def transform(x, vocab):
    assert type(x) == str, 'wrong type. x must be a sentence'
    new_representation_np = np.zeros((len(vocab)), dtype='int32')
    idx = [vocab[token] for token in x.split(' ')]
    new_representation_np[idx] = 1
    return new_representation_np    

In [58]:
transform(string, vocab=vocabulary)

array([0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int32)

In [199]:
new_docs = [
    'este documento es de programacion en castellano',
    'castellano documento en en',
]

In [215]:
def itransform(X, vocab):
    assert type(X)==type(list), 'X must be a list'
    c_idx = Counter()
    cols = len(X)
    rep = np.zeros((cols, len(vocab)), dtype='int32')
    for i, x in enumerate(X):
        tokens = [vocab[token] for token in x.split(' ') if token in vocab]
        for t in tokens:
            rep[i, t] += 1
    return rep

In [216]:
itransform(new_docs, vocabulary)

array([[0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0],
       [0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]], dtype=int32)

BoW makes us lose context. No sequence. BoW method is the most basic method we have, and for some tasks its a "good enough" baseline.